config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  root "posts#index"

  resources :users 

  resource :session, only: [:new, :create, :destroy]

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end

    alias_action :create, :read, :update, :delete, :to => :crud

    can :crud, Post do |post|
      user == post.user
    end

    can :crud, Comment do |comment|
      user == comment.user
    end

    can :update, User do |user|
      user == user
    end

    can :update, User do |password|
      user == user.password
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
     
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body, length: {minimum: 1, maximum: 200}
end

app/models/post.rb
class Post < ApplicationRecord


    has_many :comments, dependent: :destroy
    belongs_to :user


    validates :title, presence: true, uniqueness: true
    validates :body, presence: true, length: {minimum: 50}

end

app/models/user.rb
class User < ApplicationRecord
    
    has_secure_password

    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy

    # Validations 

    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX
     

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user
        @current_user ||= User.find_by_id session[:user_id]
    end

    helper_method :current_user

    def user_signed_in?
        current_user.present?
    end

    helper_method :user_signed_in?

    def authenticate_user!
        redirect_to new_session_path, alert: "Please sign in to proceed." unless user_signed_in?
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :find_post
    before_action :authenticate_user!


    def create
        @comment = Comment.new(comment_params)
        @comment.post = @post 
        @comment.user = current_user
        if @comment.save
            flash[:success] = "Comment successfully created!"
            redirect_to @post
        else
            @comments = @post.comments.order(created_at: :desc)
            render "/posts/show", status: 303 
        end
    end

    def destroy
        @comment = Comment.find params[:id]

        if can?(:crud, @comment)
            @comment.destroy
            redirect_to post_path(@comment.post)
            flash[:success] = "Comment has been deleted."
        else
            redirect_to root_path, alert: "Not authorized to change comment."
        end
        
    end

    private

    def find_post
        @post= Post.find params[:post_id]
    end

    def comment_params
        params.require(:comment).permit(:body)
    end


end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

    # Callback
  before_action :user_signed_in?
  before_action :find_user, only: [:edit, :update]
  before_action :authenticate_user!

  
# Action

    def edit
    end

    def update

        update_input = password_params

       

            if @user.authenticate(update_input[:current_password])
                if update_input[:current_password] != update_input[:new_password]
                    @user.update(password: update_input[:new_password])
                    redirect_to root_path
                    flash[:success] = "Password successfully updated."
                else
                    redirect_to password_path, alert: "New password cannot match the current one. Please try again."
                end
            else
                redirect_to password_path, alert: 'Incorrect password.'
            end
    end

    private

    def find_user
    
     @user = @current_user

    end

    def password_params

        puts params
        params.require(:user).permit(:current_password, :new_password, :new_password_confirmation)
    
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    # Callbacks

    before_action :find_post, only: [:edit, :update, :show, :destroy]

    before_action :authenticate_user!, except: [:index, :show]

    before_action :authorize_user!, only: [:edit, :update, :destroy]

    # Actions

    # Read

    def index
        @posts = Post.order(created_at: :desc)
    end

    def show
        @comments = @post.comments.order(created_at: :desc)
        @comment = Comment.new
    end

    # Create

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user = current_user
        if @post.save
            flash[:success] = "Post successfully created."
            redirect_to @post
        else
            render 'new', status: 303
        end
    end

    # Update

    def edit
    end

    def update
        if @post.update(post_params)
            flash[:success] = "Post successfully updated."
            redirect_to @post
        else
            flash[:error] = "Something went wrong."
            render 'edit' 
        end
    end

    # Delete

    def destroy
        @post.destroy
        flash[:success] = "Post successfully deleted."
        redirect_to root_path
    end

    private

    def find_post
        @post = Post.find(params[:id])

    end

    def post_params
        params.require(:post).permit(:title, :body)
    end

    def authorize_user!
        redirect_to root_path, alert: "Not authorized to change post." unless can?(:crud, @post)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end


    def create
        @user = User.find_by_email params[:email]
        
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to root_path, {notice: "Logged in"}
        else
            redirect_to new_session_path, {notice: "Wrong email or password", status: 303} 
        end
    end


    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# Callbacks

before_action :find_user, only: [:edit, :update]



# Actions


# New

    def new
        @user = User.new
    end

    def create
        @user = User.new params.require(:user).permit(
            :first_name,
            :last_name,
            :email,
            :password,
            :password_confirmation
        )

        if @user.save
            session[:user_id] = @user.id
            flash.notice = "Signed Up!"
            redirect_to root_path
        else
            render :new, status: 303
        end
    end

# Update

    def edit
    end

    def update
        

    if @user.update(user_params)
        flash[:success] = "Profile successfully updated."
        redirect_to root_path 
    else
        redirect_to users_path
        flash[:error] = "Something went wrong."
    end
       
            
    end

private

def find_user
    @user = User.find(params[:id])
end

def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
     <%= link_to 'Blog on Rails', root_path, class: "navbar-brand nav_blue_line" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
         <%= link_to 'Home', root_path, class: "nav-link active nav_blue_line"  %>
        </li>
        
        <% if(user_signed_in?) %>

            <li class="nav-item">
                <%= link_to 'New', new_post_path, class: "nav-link active nav_blue_line"%>
            </li>
            
            <li class="nav-item">
                <%= link_to current_user.first_name, edit_user_path(current_user), class: "nav-link active nav_blue_line" %>
            </li>

            <li class="nav-item">
              <div class="nav-link"><%= button_to "Log out", session_path, method: :delete, class: "btn btn-danger" %></div>
            </li>

            
        <% else %>
        
          <li class="nav-item">
              <%= link_to 'Sign In', new_session_path, class: "nav-link active nav_blue_line"%>
          </li>
          <li class="nav-item">
              <%= link_to 'Sign Up', new_user_path, class: "nav-link active nav_blue_line"%>
          </li>
          
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog on Rails</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= flash[:success] || flash[:error] %>

    <%=render "layouts/header"  %>

    <% flash.each do |type, message| %>
      <div class="alert alert-info" role=alert >
         <%= type + " " + message %>
      </div>
    <% end %>

    <div class = "container-fluid">
      <br>
      <%= yield %>
    </div>

   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post) do |form| %>

<% if @post.errors.any? %>
<ul>
 <% @post.errors.full_messages.each do |message| %>

 <li> <%= message %> </li>

 <% end %>

</ul>

 <% end %>

<div>
<%= form.label :title %>
<br>
<%= form.text_field :title %>
</div>
<br>
<div>
<%= form.label :body %>
<br>
<%= form.text_area :body, cols: 50, rows: 5 %>
</div>

<br>

<%= form.submit class:"btn btn-outline-primary" %>

<% end %>

app/views/posts/edit.html.erb
<h1> Edit Post Page </h1>

<%= render "form" %>

app/views/posts/index.html.erb
  <div class= "row justify-content-center row-cols-1 row-cols-sm-2 row-cols-md-4">
    <% @posts.each do |post| %>

        <div class = "col index" >
        
        

          <h2> <%= link_to post.title, post %></h2>
          <p> <%= truncate post.body, length:50 %></p>

        

        </div>

        <br>

        <% end %>
    </div>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<p> <%= @post.body %> </p>
<p><small> Created <%= time_ago_in_words(@post.created_at) %> ago </small></p>
<p><small> Created by <%= @post.user.first_name %> </small></p>
<div class="d-flex">
    <div class="m-1">
        <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-outline-primary" %>
    </div>
 
    <div class="m-1">
        <%= button_to 'Delete', post_path(@post), method: :delete, form: {data: {turbo_confirm: "Are you sure you would like to proceed?"}}, class:"btn btn-outline-primary" %>
    </div>
</div>

<br>

<h4> Comment </h4>

<% if @comment.errors.any? %>
   <ul>
     <% @comment.errors.full_messages.each do |message| %>

     <li> <%= message %> </li>

      <% end %>

    </ul>

 <% end %>

 <%= form_with(model: [@post, @comment]) do |form| %>
 
 <div>

 <% form.label :body%>
 
 <%= form.text_area :body, placeholder: "What's on your mind?", cols: 50, rows: 5%> 
 <br>
 <br>
 <%= form.submit "Submit", class:"btn btn-outline-primary" %>

 </div>
 <% end %>

<br>

<div>
<% @comments.each do |comment| %>

<div>
 <%= comment.body %> <br>
 <small> Commented <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user.first_name %> ⦁ </small>
 <%=link_to "Delete", post_comment_path(@post.id, comment.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>
<br>

<% end %>
</div>

app/views/users/edit.html.erb
<h1> Update Your Profile </h1>

<% if @user.errors.any? %>
    <p> <%= @user.errors.full_messages.join(',') %> </p>
<% end %>

<%= form_with model: @user do |form| %>

<form>
  <div class="mb-3">
        <%= form.label :first_name %>
        <br>
        <%= form.text_field :first_name, placeholder: current_user.first_name %>
  </div>

  <div class="mb-3">
        <%= form.label :last_name %>
        <br>
        <%= form.text_field :last_name, placeholder: current_user.last_name %>
  </div>

  <div class="mb-3">
        <%= form.label :email %>
        <br>
        <%= form.text_field :email, placeholder: current_user.email %>
  </div>

  <br>

  <%= form.submit "Update", method: :patch, class:"btn btn-outline-primary" %>

  <% end %>

  <br>

 <h1> Need to Change Your Password? </h1>

 <br>



 <div>
        <%= link_to 'Click Here', password_path(@user), class:"btn btn-outline-primary" %>
 </div>

 

app/views/users/new.html.erb
<h1> Sign Up </h1>

<% if @user.errors.any? %>
    <p> <%= @user.errors.full_messages.join(',') %> </p>
<% end %>

<%= form_with model: @user do |form| %>

<form>
  <div class="mb-3">
        <%= form.label :first_name %>
        <br>
        <%= form.text_field :first_name %>
  </div>

  <div class="mb-3">
        <%= form.label :last_name %>
        <br>
        <%= form.text_field :last_name %>
  </div>

  <div class="mb-3">
        <%= form.label :email %>
        <br>
        <%= form.text_field :email %>
  </div>

  <div class="mb-3">
        <%= form.label :password %>
        <br>
        <%= form.password_field :password %>
  </div>
  
  <div class="mb-3">
        <%= form.label :password_confirmation %>
        <br>
        <%= form.password_field :password_confirmation %>
  </div>

   
        <%= form.submit "Sign Up", class: "btn btn-primary" %>
   

</form>
  


<% end %>